databases:
  - name: ezPay
    ipAllowList: []
    databaseName: ezpay_cttk
    user: ezpay_cttk_user


services:
  - type: web
    name: budgetApp
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ezPay
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false