default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: fatema
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ezPay_development
  

test:
  <<: *default
  database: ezPay_test
  

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
