default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ezPay-rails-app_development
  username: postgres
  password: fatema
  host: localhost

test:
  <<: *default
  database: ezPay-rails-app_test
  username: postgres
  password: fatema
  host: localhost

production:
  <<: *default
  database: ezPay-rails-app_production
  username: postgres
  password: fatema
  host: localhost
